name: Bug report
description: Report a reproducible defect in pubmed-cli.
title: "[bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What failed?
      placeholder: One-sentence summary of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction
      description: Include exact command(s) and output.
      placeholder: |
        pubmed search "autism" --limit 0
        Error: --limit must be greater than 0
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `pubmed --version` or release tag.
      placeholder: v0.5.1
    validations:
      required: true

  - type: dropdown
    id: install_method
    attributes:
      label: Install method
      options:
        - Homebrew
        - go install
        - Built from source
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, shell, and any relevant env vars (mask secrets).
      placeholder: macOS 14, zsh, NCBI_API_KEY set
