name: Feature request
description: Propose an improvement for pubmed-cli.
title: "[feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What workflow is blocked today?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe command shape and expected behavior.
      placeholder: Add --foo to `pubmed search` to ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or competing designs?

  - type: textarea
    id: examples
    attributes:
      label: Example usage
      description: Concrete CLI examples are preferred.
      placeholder: |
        pubmed search "glioblastoma" --foo
